### ISSUE TITLE
Immutable Collections

### ISSUE THREAD

**Issue by benjamin-hodgson** [wojciechsura/Spooksoft.Xml.Serialization#1]
Does your library support (de)serialising the classes in `System.Collections.Immutable`? I'm especially keen to use `ImmutableArray`.

Thanks!

**Comment by wojciechsura** [comment]
My library doesn't support `ImmutableArray` (yet), and I can't work on this project right now. However, I encourage you to try and add the support for this type by yourself. Basically as I see it, the implementation would be extremely similar to the [one for List<T>](https://github.com/wojciechsura/Spooksoft.Xml.Serialization/blob/master/Spooksoft.Xml.Serialization/Infrastructure/CollectionSerializers/ListSerializer.cs). Serialization of all collections is covered by a number of helper methods, which do the heavy lifting. More specifically, the serialization can be done exactly the same way as for `List<T>` and deserialization would require only one additional step: first, deserializing XML into a `List<T>` (one line) and then creating an `ImmutableArray<T>` from the deserialized list (one line).

Afterwards just add a single line in the [collection serializer repository](https://github.com/wojciechsura/Spooksoft.Xml.Serialization/blob/master/Spooksoft.Xml.Serialization/Infrastructure/CollectionSerializerProvider.cs) to support the new type and you're done :)

I welcome all pull requests, just please add at least one unit test for the new implementation.

**Comment by wojciechsura** [comment]
I have added support for ImmutableArray<T>.

In case you need support for more collection types, please take a look at implementations in [CollectionSerializers](https://github.com/wojciechsura/Spooksoft.Xml.Serialization/tree/master/Spooksoft.Xml.Serialization/Infrastructure/CollectionSerializers) folder - implementing another collection serializer is actually quite a simple task (when using helper methods provided in base classes). Afterwards you just need to register one more serializer in [CollectionSerializerProvider](https://github.com/wojciechsura/Spooksoft.Xml.Serialization/blob/master/Spooksoft.Xml.Serialization/Infrastructure/CollectionSerializerProvider.cs) class. Finally, add a unit test, which checks if serialization works as intended.

Pull requests are very welcome :)

**Comment by benjamin-hodgson** [comment]
Thank you!
